### DISCUSSION TITLE
Style Improvement - Larger Heading Margin and Size

### DISCUSSION THREAD

**Discussion by rmorshea** [pradyunsg/furo#219] [Ideas] [answered]
Right now, the top margin above headings as well as their font size/weight deemphasizes sections on the page. This can lead to a sense that one section bleeds into another. Thus, making it harder to focus on one section as a time.

I've added the following custom CSS to my documentation using this theme and, while I'm no CSS wizard, I think it looks better. 

```css
h1,
h2,
h3,
h4,
h5,
h6 {
  margin-top: 2em !important;
  margin-bottom: 0 !important;
  font-weight: 900 !important;
}

h2 {
  font-size: 1.8em !important;
}

h3 {
  font-size: 1.4em !important;
}
```

Here's some before and after screenshots:

---

**Before**

![image](https://user-images.githubusercontent.com/4041990/130202684-b14b0925-ac47-424e-9669-0b2bda753381.png)

---

**After**

![image](https://user-images.githubusercontent.com/4041990/130202339-2d58ede8-5b6b-4161-855a-b537d17d59d9.png)
