### DISCUSSION TITLE
python module imports get underlines

### DISCUSSION THREAD

**Discussion by jkittner** [pradyunsg/furo#221] [Questions] [answered]
Hi, thanks for creating this awesome theme!
I am a bit confused with the new gh discussions thingy, not sure if I am even at the right place for an issue now, sorry if not...

I think there is an issue with the `css` for the dark theme -- imports in python code blocks get an underline, which I don't think is intended:
![grafik](https://user-images.githubusercontent.com/54631600/130629266-c30ecfac-91cf-442c-842d-740cec97428e.png)
This does only happen in the dark theme, the light theme is fine:
![grafik](https://user-images.githubusercontent.com/54631600/130629334-b2d55fc4-f6d2-4abb-9d3d-cdc777578bd9.png)

I think the issue comes from the `pygments_dark.css` and the `.nn` class
```css
body[data-theme="dark"] .highlight .nn { color: #447fcf; text-decoration: underline } /* Name.Namespace */
```
so I guess the `text-decoration` should be `none` here, to avoid the underline. Maybe this is an issue in `pygments` itself though?
