### DISCUSSION TITLE
No support for non-arabic list styles

### DISCUSSION THREAD

**Discussion by ghost** [pradyunsg/furo#235] [Potential Issue] [answered]
Furo misses to define a list-style for non-arabic lists.  This makes nested list look very ugly, as they are all numbered with 1., 2.

Example:

```rst
1. 1st

   a) a-ish

      i) i-ish
      ii) i-ish
   b) b-ish
2. 2nd

   A) a2-ish
   B) b2-ish
   C) c2-ish
3. third
```
You can also see it in the kitchen sink: https://pradyunsg.me/furo/kitchen-sink/lists_tables/

Proposed Solution:  Sphinx (or docutils) adds a class to html ``ol`` item indication which style it was in ReST.
Here is a CSS snippet with the required rules detecting that class.  The rules are taken from Sphinx (themes/basic/static/basic.css_t)

```css
ol.arabic {
    list-style: decimal;
}

ol.loweralpha {
    list-style: lower-alpha;
}

ol.upperalpha {
    list-style: upper-alpha;
}

ol.lowerroman {
    list-style: lower-roman;
}

ol.upperroman {
    list-style: upper-roman;
}
```
(Sorry, don't speak sass.)
