### DISCUSSION TITLE
Switch light/dark background color for sidebar-scroll

### DISCUSSION THREAD

**Discussion by edgarriba** [pradyunsg/furo#269] [Questions] [answered]
Hi - is it possible to overwrite for light/dark mode the background-color of the sidebar-scroll ?

Now I do directly on the css but only for light

```css
.sidebar-scroll p.caption{
    background-color: #4d59ff;
}
```
see results (I would like to make the dark less colorful)

![image](https://user-images.githubusercontent.com/5157099/135118850-3908682d-fbd8-4834-8046-9f891c052931.png)
