### DISCUSSION TITLE
Sidebar stays in floating mode when max-width is reached

### DISCUSSION THREAD

**Discussion by hroemer** [pradyunsg/furo#342] [Potential Issue] [answered]
Thanks for the great theme that works like a charm and has a very clean design :+1: 

However I am experiencing some minor glitches, like sidebars staying in "floating mode" independent of media width. The current rendered CSS looks like this:

```css
@media (max-width: 46em) {
    .content {
        padding: 0 1em
    }

    article div.sidebar {
        float: none;
        margin: 1rem 0;
        width: 100%
    }
}
```

It should be 

```css
@media (max-width: 46em) {
    .content {
        padding: 0 1em
    }

    article aside.sidebar {
        float: none;
        margin: 1rem 0;
        width: 100%
    }
}
```
hence `aside.sidebar` instead of `div.sidebar`.
