### DISCUSSION TITLE
Inconsistent line-height for dark/light theme

### DISCUSSION THREAD

**Discussion by hroemer** [pradyunsg/furo#344] [Potential Issue] [answered]
The line-height is currently inconsistent between dark and light themes:

```css
body[data-theme="dark"] .highlight pre {
    line-height: 125%;
}
```

vs. default

```css
article .highlight pre {
    line-height: 1.5;
}
```

which becomes obvious when toggling between the two.
It might be due to different handling of the dark theme, but I couldn't figure out how `_get_styles()` works, yet:

```python
    light_formatter = HtmlFormatter(style=_KNOWN_STYLES_IN_USE["light"])
    dark_formatter = HtmlFormatter(style=_KNOWN_STYLES_IN_USE["dark"])

    lines: List[str] = []

    lines.extend(_get_styles(light_formatter, prefix=".highlight"))

    dark_prefix = 'body[data-theme="dark"] .highlight'
    lines.extend(_get_styles(dark_formatter, prefix=dark_prefix))

    not_light_prefix = 'body:not([data-theme="light"]) .highlight'
    lines.append("@media (prefers-color-scheme: dark) {")
    lines.extend(_get_styles(dark_formatter, prefix=not_light_prefix))
    lines.append("}")
```

Any ideas?

**Comment by pradyunsg** [comment]
Hmm... What version are you on? I believe this has been fixed.

**Reply by hroemer** [reply]
I am using the recent version `2021.11.23`.

**Reply by pradyunsg** [reply]
I'm unable to reproduce this on MacOS + Firefox 95 + 2021.11.23. This might be something that originates from the specific pygments themes that you're using, if you've overridden the defaults. 🤷🏽

**Reply by hroemer** [reply]
Very strange!? Not setting the pygment styles still shows the same results on Linux + furo `2021.11.23` + pygments `2.11.1` independent of the used browser (although the browser should not have an impact on the CSS in the HTTP response anyhow).
I will try to make a repro.

**Reply by pradyunsg** [reply]
Ah! This was fixed in https://github.com/pradyunsg/furo/commit/0c4018fa730d12dc2144745b75c33b922b7cf7d4 -- which isn't in any release. :)

**Comment by pradyunsg** [comment, marked as answer]
Fixed in https://github.com/pradyunsg/furo/commit/0c4018fa730d12dc2144745b75c33b922b7cf7d4. Will be in the next release.

**Reply by pradyunsg** [reply]
Released.

**Comment by hroemer** [comment]
I double-checked 0c4018f, it works pretty good, thanks!

One open issue though: the line number padding is also off. I had to additionally override it like this:

```css
article[role=main] {
  .highlight span.linenos {
    color: inherit;
    background-color: transparent;
    padding-left: 0.875rem;
    padding-right: 0.875rem;
  }
}
```

So I guess this part of _code.sass needs to be adjusted as well here:

```sass
// When `html_codeblock_linenos_style` is inline.
.highlight
  span.linenos
    display: inline-block
    padding-left: 0
    padding-right: $code-spacing-horizontal
    margin-right: $code-spacing-horizontal
    box-shadow: -0.0625rem 0 var(--color-foreground-border) inset

```
