### DISCUSSION TITLE
Permalink markers not visible for targets with custom labels

### DISCUSSION THREAD

**Discussion by pocek** [pradyunsg/furo#347] [Potential Issue] [answered]
Furo has a code like this:

```sass
h1,
h2,
h3,
h4,
h5,
h6
  :target > &:first-child > .headerlink
    visibility: visible
```

The problem is, if section has a custom label (like in [Cross-referencing arbitrary locations](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-arbitrary-locations)), the header is not a first child anymore, so the marker is not visible. I currently patch this with a CSS:

```css
/* Fix for custom labels */
:target > h1:nth-of-type(1) > .headerlink,
:target > h2:nth-of-type(1) > .headerlink,
:target > h3:nth-of-type(1) > .headerlink,
:target > h4:nth-of-type(1) > .headerlink,
:target > h5:nth-of-type(1) > .headerlink,
:target > h6:nth-of-type(1) > .headerlink {
    visibility: visible;
}
```

The key here is to use `:nth-of-type(1)` instead of `:first-child`.
