### DISCUSSION TITLE
Add support for `style_external_links`

### DISCUSSION THREAD

**Discussion by harshil21** [pradyunsg/furo#348] [Ideas] [answered]
Hi! Thanks for making this theme!

I was just switching from a read the docs theme to furo, and stumbled upon this warning:

`WARNING: unsupported theme option 'style_external_links' given`

As you can see, I'm using intersphinx, and it would be nice to have this included.

Furo version: 2022.1.2
Sphinx version: 4.3.2

**Comment by pradyunsg** [comment]
I have no idea what this is supposed to do even. Can you please elaborate on what this option is supposed to be for? I imagine this is a theme-specific option from some theme you use?

> As you can see, I'm using intersphinx, and it would be nice to have this included.

No, in fact, I can't.

**Reply by Bibo-Joshi** [reply]
It's a setting of the `sphinx_rtd_theme`, see [here](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-style_external_links). I guess the question is to add a similar config value to Furo :)

**Comment by pradyunsg** [comment, marked as answer]
It's unlikely that I'd add such an option to this theme.

I've intentionally not provided/implemented such configuration options with this theme. Supporting one-off features like this, that only a few projects would want, is not something I'm keen on doing. My bias here is straightforward: I'd like to keep things at a minimum here because I only have so much time. The less that this theme provides/does directly, the easier it is for me to "keep the lights on" for it. :)

For your usecase, you should be able to [inject CSS](https://pradyunsg.me/furo/customisation/injecting/) like the following, to achieve what you're looking for:

```css
article a.reference.external::after {
      content: url('data:image/svg+xml,<svg width="12" height="12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="1.5" stroke="%23607D8B" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><path d="M11 7h-5a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-5" /><line x1="10" y1="14" x2="20" y2="4" /><polyline points="15 4 20 4 20 9" /></svg>');
      margin: 0 0.25rem;
      vertical-align: middle;
}
```

Feel free to change this up, to stylize external links however you like. :)
