### DISCUSSION TITLE
Failure when building in Readthedocs

### DISCUSSION THREAD

**Discussion by mendax1234** [pradyunsg/furo#419] [Questions] [answered]
### What's happening?

![image](https://user-images.githubusercontent.com/62934294/163533871-ee8cdb26-40c9-4b11-8a0a-1152f6198186.png)
l want to change my theme to Furo but when l build it on the readthedocs, it fails.

### Reproducer

1. Build Sphinx documentation at 'Sphinx 4.5.0' (include build instructions)
2. Go to '...'
3. Click on '...'
4. Scroll down to '...'
5. See wrong thing.

### Expectation

Hope anyone can help me!

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by pradyunsg** [comment, marked as answer]
You should have files that look something like this in your repository:

docs/requirements.txt

```
sphinx
lutra
```

.readthedocs.yml

```yaml
version: 2

sphinx:
  builder: htmldir
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
```
