### DISCUSSION TITLE
Fixed position for announcement banner

### DISCUSSION THREAD

**Discussion by alexisthual** [pradyunsg/furo#545] [Ideas] [answered]
Hi!

I think it'd be nice if the announcement banner had a fixed position (maybe users could choose whether the position is fixed or not).

My motivation is the following: I use announcement banners to warn users that they're looking at an outdated version of the docs. People accessing outdated pages of the docs at paragraphs that are at the bottom of the page will not see the announcement, and it can be very misleading.

Let me know what you think :slightly_smiling_face:

**Comment by pradyunsg** [comment]
This can be achieve by adding the following custom CSS today.

```css
.announcement {
    position: fixed;
    width: 100%;
    z-index: 100;
}

.announcement + .page {
    padding-top: var(--header-height);
}
.announcement + .page .mobile-header {
    top: var(--header-height);
}
```

I'll think about if/how this should be included as a configuration option in Furo itself. :)
