### DISCUSSION TITLE
Napoleon rubrics (e.g., EXAMPLE) not formatted correctly.

### DISCUSSION THREAD

**Discussion by sscherfke** [pradyunsg/furo#573] [Potential Issue]
Some docstring sections/rubrics from Napoleon (e.g., Example(s)) are not rendered as `<dt>` but as `<p class="rubric">`. Furo does not style them in the same ways as PARAMETER or RETURN. It is not as bold (400, but should be 500) and the trailing `:` is missing.

I currently have the following CSS rules in a custom CSS file to fix this:
```css
dd p.rubric {
  font-weight: 500;
}
dd p.rubric::after {
  content: ":";
}
```
