### DISCUSSION TITLE
Potentially inaccessible drawers on mobile

### DISCUSSION THREAD

**Discussion by tfardet** [pradyunsg/furo#690] [Potential Issue]
On mobile, people who use large fontsize or zoom can easily get the ToC drawer to span the size of the screen.
As the only way to remove the drawer is to click away from it, this means that they are completely stuck on the ToC (especially so since clicking on the anchors does not hide the ToC) with no way of collapsing it again.

Would it be possible to add a way to collapse the drawer without clicking away from it?

Note 1: the menu is also affected but since clicking on a link collapses it, the issue is less severe there.

Note 2: the following CSS makes the issue worse by putting some/most of the text outside the screen area

```css
.sidebar-container, .toc-drawer {
  box-sizing: border-box;
  width: 15em; /* problematic bit, removing it keeps the text on-screen */
}
```

**Steps to reproduce:** make your window very narrow (like on mobile) and zoom until ToC drawer fills the screen.
