### DISCUSSION TITLE
Over-indented closing parenthesis when `maximum_signature_line_length` is set

### DISCUSSION THREAD

**Discussion by tqbl** [pradyunsg/furo#749] [Potential Issue]
When enabling signature line breaks via `maximum_signature_line_length`, the closing parenthesis is over-indented. 

Here is an example of what it looks like:
<img width="379" alt="example" src="https://github.com/pradyunsg/furo/assets/9166599/b1deadd3-4425-4e93-979e-be4cc03eee5f">

I'm assuming this isn't intentional. Even if the intention was to align the closing parenthesis with the parameters, the parenthesis is still a little off. It looks like the issue is caused by these two properties:
```css
.sig:not(.sig-inline) {
    /* Other properties have been omitted. */
    padding-left: 3em;
    text-indent: -2.5em;
}
```
If I override these properties with a `custom.css` file, it seems to fix the issue:
```css
.sig:not(.sig-inline) {
    padding-left: 0.5em;
    text-indent: 0;
}
```
But of course this will cause problems when `maximum_signature_line_length` is *not* set.

Is there a universal fix that could be applied?
