### DISCUSSION TITLE
Copy Button Covers the End of Long Lines

### DISCUSSION THREAD

**Discussion by holesch** [pradyunsg/furo#781] [Potential Issue] [answered]
I have some code blocks with a single long line (long enough to have a horizontal scroll bar). With sphinx-copybutton enabled, even when I scroll to the end, then the button covers the last few characters.

The style from sphinx-copybutton makes the button invisible by default and it only fades in when hovering over the code block. The style from Furo overwrites this and makes the button always visible.

I fixed this with a custom.css in my project, but this could be beneficial for all:
```css
.highlight button.copybtn {
    /* Show copy button only while hovering over the code block, to make long
     * lines readable */
    opacity: 0;
}
```
