### DISCUSSION TITLE
Optionally configure ONLY light and dark themes, no auto theme?

### DISCUSSION THREAD

**Discussion by cmoliverio** [pradyunsg/furo#857] [Ideas] [answered]
Hey folks,

I'm using the furo theme to host a documentation page for my [FRC team as a GitHub page](https://github.com/frc4206/battleaid/tree/main/pages/source).  I was running into some issues using CSS in combination with the sphinx-build `conf.py` where, when the page was opened with the `auto` theme, it would use the dark mode logo but the light mode theme settings.  

What this is really led to is that I want an option to _only_ have the light and dark mode options and remove the 'auto' one entirely.  Then I don't have to worry about funky behavior when I try to use CSS and so forth. 

For example; I imagine my `conf.py` looking something like this: 

```python
html_theme = 'furo'
html_title = ""
html_static_path = ['_static']

html_css_files = [
    # the theme file contains some settings for the light and dark mode
    "theme_file.css"
]

html_theme_options = {
    "light_logo": "images/light-logo.png",
    "dark_logo": "images/dark-logo.png",
    # some parameter here to disable the auto theme and button
}
```

The `theme_file.css` containts this: 

```css
/* Variables for colors */
:root {
    --blue: #031db0;
    --background-color: #eaeef3;
}

[data-theme="dark"] {
    --blue: #366aca;
    --background-color: #4184ff;
}

/* Logo settings */
.sidebar-logo {
    background-color: var(--background-color);
    border-radius: 15px;
}

[data-theme="dark"] .sidebar-logo {
    background-color: var(--background-color);
}
```

I don't know the best way to do that option, but I guess it makes the most sense to allow the user to specifically choose which themes they want to allow the page to have.  For instance:

```python
html_theme_options = {
    "furo_theme_list" = [ "light", "dark" ]  # and then the user could add 'auto' or not
}
```

Or, if they wanted to ONLY have the dark mode:

```python
html_theme_options = {
    "furo_theme_list" = [ "dark" ] 
}
```

Obviously the default is that all three are enabled.

Is it possible to add this this feature?  Do you folks this is a good idea?  I looked through the source of `furo` and I think I could even add this change myself with enough effort, but if I could either get feedback or a thumbs up that would be great.   I didn't see a similar request for this already.

Thanks yall!
