### DISCUSSION TITLE
Wrong ReadTheDocs Addons notification font size

### DISCUSSION THREAD

**Discussion by Metadorius** [pradyunsg/furo#868] [Potential Issue]
The font seems to be changed from the default one for some reason:

![image](https://github.com/user-attachments/assets/53cf4207-4cc7-44ae-b253-2112779da373)

Relevant config PR (with the fix applied): https://github.com/Phobos-developers/Phobos/pull/1526

Adding this as custom CSS seems to work:
```css
:root {
  --readthedocs-notification-font-size: 1rem;
}
```
