### DISCUSSION TITLE
rendering of latex equation in dark mode

### DISCUSSION THREAD

**Discussion by Remi-Gau** [pradyunsg/furo#874] [Potential Issue]
We encountered a small issue on our doc where latex equation were hard to view in dark mode:

https://github.com/nilearn/nilearn/issues/5210

![image](https://github.com/user-attachments/assets/095ae14d-187e-4a13-b148-58a27d1442e5)

![image](https://github.com/user-attachments/assets/22a701e5-b4f5-4b8a-a7f7-6ddf2e274cad)

also it often felt like latex images (img with a 'math' class) were always a bit higher than the rest of the text when inlined

the way we will probably fix this is by adding this to our custom css:

https://github.com/nilearn/nilearn/pull/5213/files

```css
/* Latex images
latex equation are inserted as images but are bit higher
than the rest of the text and do not play nice with dark mode
*/

img.math {
  transform: translateY(2px);
}

/* Light Mode */
[data-theme="light"] img.math {
  filter: invert(0);
}

/* Dark Mode */
[data-theme="dark"] img.math {
  filter: invert(1);
}

/* Auto Mode - Uses System Preference */
[data-theme="auto"] img.math {
  filter: invert(0);
}

@media (prefers-color-scheme: dark) {
  [data-theme="auto"] img.math {
    filter: invert(1);
  }
}
```

if there is a better way, feel free to chime in
