### DISCUSSION TITLE
Theming (light/dark mode) for Graphviz?

### DISCUSSION THREAD

**Discussion by qwertychouskie** [pradyunsg/furo#877] [Ideas]
By default, anything output from Graphviz just uses default colors, which is pretty jarring in dark mode:
![image](https://github.com/user-attachments/assets/2eaffa68-8274-4d63-91e3-cd508b572ad1)

Currently we use a bit of a CSS hack to make it look better:
```
@media (prefers-color-scheme: dark) {
    /* Make diagrams look (mostly) correct in dark mode */
    img.graphviz, object.graphviz {
        filter: invert(87%);
    }
}
```
That makes it look like this:
![image](https://github.com/user-attachments/assets/0b57d49e-c5c3-410f-8e7e-ea5f1a9ce8aa)

While it's certainly an improvement, it's a bit hacky and the background color visibly doesn't match.  The "Sphinx-Immaterial" theme seems to have a better solution, where it actually uses the theme colors in the SVG: https://jbms.github.io/sphinx-immaterial/graphviz.html  It would be nice to have something similar in furo.

**Comment by bimac** [comment]
I know, I'm late to the party, but I just stumbled across this ... very helpful!

To get rid of the background entirely, combine a full inversion with a screen blend:

``` css
@media (prefers-color-scheme: dark) {
    img.graphviz, object.graphviz {
        filter: invert();
        mix-blend-mode: screen;
    }
}
```
