### ISSUE TITLE
Dark Mode Scrollbar on Linux + Blink

### ISSUE THREAD

**Issue by rmorshea** [pradyunsg/furo#101]
There's currently no styling for the scroll bar in darkmode which causes it to stand out more than it should:

![image](https://user-images.githubusercontent.com/4041990/111096775-82bdc800-84fd-11eb-95b9-d02b0eaa0918.png) light ![image](https://user-images.githubusercontent.com/4041990/111096822-a54fe100-84fd-11eb-9f42-8435584b2640.png) dark

I'm currently using some custom CSS to produce the following scroll bar looks:

![image](https://user-images.githubusercontent.com/4041990/111098999-d3372480-8501-11eb-8a15-2bbcfe332e39.png) light ![image](https://user-images.githubusercontent.com/4041990/111099038-e8ac4e80-8501-11eb-963f-a342dcd72b7e.png) dark

The CSS itself is below. I've just used colors from the available CSS variables, so the look could be improved by adding new ones:

```css
::-webkit-scrollbar {
  width: 16px;
  height: 16px;
}

::-webkit-scrollbar-corner,
::-webkit-scrollbar-track {
  background-color: var(--color-background-border);
}

::-webkit-scrollbar-thumb {
  background-color: var(--color-foreground-border);
  background-clip: padding-box;
  border: 2px solid transparent;
}

/* Buttons */
::-webkit-scrollbar-button:single-button {
  background-color: var(--color-background-border);
  display: block;
  background-size: 10px;
  background-repeat: no-repeat;
}

/* Up */
::-webkit-scrollbar-button:single-button:vertical:decrement {
  height: 12px;
  width: 16px;
  background-position: center 4px;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' fill='var(--color-background-border)'><polygon points='50,00 0,50 100,50'/></svg>");
}

/* Down */
::-webkit-scrollbar-button:single-button:vertical:increment {
  height: 12px;
  width: 16px;
  background-position: center 2px;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' fill='var(--color-background-border)'><polygon points='0,0 100,0 50,50'/></svg>");
}

/* Left */
::-webkit-scrollbar-button:single-button:horizontal:decrement {
  height: 12px;
  width: 12px;
  background-position: 3px 3px;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' fill='var(--color-background-border)'><polygon points='0,50 50,100 50,0'/></svg>");
}

/* Right */
::-webkit-scrollbar-button:single-button:horizontal:increment {
  height: 12px;
  width: 12px;
  background-position: 3px 3px;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' fill='var(--color-background-border)'><polygon points='0,0 0,100 50,50'/></svg>");
}
```
