### ISSUE TITLE
scrollbar issue in sidebars

### ISSUE THREAD

**Issue by bastimeyer** [pradyunsg/furo#36]
**Describe the bug**
As mentioned in #32, both sidebars still have issues with the scrollbars.

On the current page's TOC sidebar on the right, `overflow: auto` gets set on hover. This is a big problem here, as it reduces the available horizontal space of the content when the scrollbar appears, and text lines can be wrapped when the space shrinks, which results in the entire content below of that line moving a couple of pixels, which is very annoying.

The main menu sidebar on the left does have the same problem when the available vertical space of the document window changes. This is especially a problem when there's content in the sidebar which is center-aligned, like for example a logo.

**Demonstration**
https://youtu.be/LH7llgLyIXs

**Expected behavior**
Both sidebars' content should have a width set, so that the scrollbar, once it appears, doesn't shrink the available space.

This worked for me as a simple workaround, but unfortunately requires defining the sidebar width myself, as it's [hardcoded in a SASS variable](https://github.com/pradyunsg/furo/blob/fa726f7471270e27e8a2ac32f7423e492426bc0b/src/furo/assets/styles/_scaffold.sass#L56-L59):
```css
:root {
  --sidebar-width: 15rem;
  --sidebar-content-width: calc(var(--sidebar-width) - 1rem);
}
.sidebar-container,
.toc-drawer {
  width: var(--sidebar-width);
}
.sidebar-scroll > *,
.toc-title-container,
.toc-tree-container {
  width: var(--sidebar-content-width);
}
.sidebar-brand {
  padding: var(--sidebar-item-spacing-vertical) 0;
}
```

The problem with this is that it assumes that the scrollbar width is `1rem`, but this should be fine in most cases.

**Desktop (please complete the following information):**

- Arch Linux
- Chromium
- 87

**Smartphone (please complete the following information):**

Not tested

**Comment by pradyunsg** [comment]
Fixed in https://github.com/pradyunsg/furo/commit/772b813b28e103668d0238a18b636b583e91bf0f (and follow up commits).

**Comment by pradyunsg** [comment]
Released the fix as part of beta 19. Let me know if that's not good-enough. :)

**Comment by bastimeyer** [comment]
I don't want to open a new issue for this, but

1. You've ignored the issue of the centered sidebar content jumping when the scrollbar appears, as I've mentioned above and shown in my linked demonstration video.

   It's not a big problem to fix this on the theme implementor side, but since the sidebar and scrollbar widths are hardcoded by the theme stylesheet, the fix needs to use hardcoded values as well.

   To properly fix this issue, **the sidebar content elements need to have set a width**:
   ```css
   .sidebar-scroll > * {
     /* hardcoded sidebar width minus hardcoded scrollbar width */
     width: calc(15rem - .25rem);
     /* quick workaround for horizontal padding values of .sidebar-brand affecting its final width */
     box-sizing: border-box;
   }
   ```
2. You probably want to add a padding-right value to the TOC sidebar elements, so that the text can't touch the scrollbar in certain "edge" cases.
   ```css
   .toc-title,
   .toc-tree > ul {
     padding-right: .5em;
   }
   ```
3. in 40acea53f382be77a09e3123d2d54e008c665304 you probably meant this CSS selector
   ```css
   :not(html):not(body)
   ```
   instead of just
   ```css
   :not(html)
   ```
   because otherwise, it styles the vertical scrollbar of the entire document body, which is a bad user experience, as the scrollbar is narrow, and that's only supposed to be on the sidebars and code boxes in the page content.
