### ISSUE TITLE
Fix indentation magic when `maximum_signature_line_length` is used

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#761]
### Discussed in https://github.com/pradyunsg/furo/discussions/749

x-ref https://github.com/pradyunsg/furo/discussions/696 which is related, and https://github.com/sphinx-doc/sphinx/pull/11011 which added this feature to Sphinx.

**Comment by tybug** [comment]
We just ran into this in Hypothesis (https://github.com/HypothesisWorks/hypothesis/pull/4310), and used the css suggested by @tqbl in #749 to fix it (thanks!):

```css
.sig:not(.sig-inline) {
    padding-left: 0.5em;
    text-indent: 0;
}
```
